spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://192.168.174.128:3306/gulimall_pms?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.174.128:8848
    application:
        name: gulimall-product

mybatis-plus:
    mapper-locations: classpath:/mapper/**/*.xml #配置xml位置
    global-config:
        db-config:
            id-type: auto #设置id自增
            logic-delete-value: 1 #逻辑已删除值
            logic-not-delete-value: 0
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
    port: 10001
logging:
    level:
        com.atguigu.gulimall: debug
feign:
    client:
        config:
            default:
                connectTimeout: 60000
                readTimeout: 60000
