#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.174.128:3306/gulimall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.174.128:8848
#  application:
#    name: gulimall-coupon
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml #配置xml位置
#  global-config:
#    db-config:
#      id-type: auto #设置id自增
#
#server:
#  port: 7000 #服务端口
