spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.174.128
    port: 6379
server:
  port: 20000