spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.174.128
    port: 6379
  session: #session 存储类型
    store-type: redis

server:
  port: 20000
  servlet: #session 过期时间 30天
    session:
      timeout: 43200


## TODO 这里该如何配置服务调用时间呢？？？
#ribbon:
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
feign:
  client:
    config:
      default:
        connectTimeout: 10000    # 10秒连接超时
        readTimeout: 30000      # 30秒读取超时
