 spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.174.128:3306/gulimall_oms?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 192.168.174.128
    port: 5672
    virtual-host: /
    publisher-confirms: true # 开启发送端确认
    publisher-returns: true  # 开启发送端抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调我们这个returnConfirm

 mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #配置xml位置
  global-config:
    db-config:
      id-type: auto #设置id自增

 server:
   port: 9000

