spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.174.128
    port: 6379
  session:
    store-type: redis

server:
  port: 12001
